# Site
repository: arguellesperezm/arguellesperezm.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Martin Arguelles Perez
title: Robotics & UAS Developer
email: arguellesperez.m@gmail.com
website: arguellesperezm.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  arguellesperezm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! 

  I am most skilled in: <mark>PX4</mark> and <mark>ROS</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      #      - layout: top-middle
      #        title: Super awesome project
      #        link: github.com/sproogen
      #        # link_text: Project Website
      #        additional_links:
      #          - title:  sproogen/modern-resume-theme
      #            icon: fab fa-github
      #            url: github.com/sproogen/modern-resume-theme
      #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #          #   icon: fab fa-github
      #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #        quote: >
      #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
      #        description: | # this will include new lines to allow paragraphs
      #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      - layout: top-middle
        title: Queit and Efficient Vertical Take-off and Landing Vehicle
        #link: github.com/sproogen
        # link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Unique capabilities of vertical lift and hover provides potential for exceptional access and mobility in both commercial and public good applications
        description: | # this will include new lines to allow paragraphs
          This project has the aim of developing a low-cost design for a vertical takeoff and landing (VTOL) vehicle.
          The designs will be tilt-rotor vehicles, and the designs will be openly available for others to use and contribute to.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Nevada, Las Vegas
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: January 2021 - Present
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Building new UAS systems and adding functionality.
            Autonomous control of drones using PX4 Autopilot.
            Programming firmware for PX4 to be flashed onto flight controller.
      - layout: left
        title: Nevada System of Higher Education
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: STEM Tutor
        caption: January 2019 - October 2021
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As a tutor, I guided students through their coursework.
            Identifying and addressing deficiencies is critical to a student’s success.
            Communication is paramount to supplementing students’ understanding.
      - layout: left
        title: Tesla
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: New Homes Photovoltaic Designer
        caption: July 2017 - June 2018
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Analyzed the aspects of new housing developments to consult sales regarding photovoltaic systems that could remain consistent throughout the community.
      - layout: left
        title: Solarcity
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Photovoltaic Designer
        caption: March 2015 - July 2017
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Information from surveyors was used to create a photovoltaic (solar) system for residential projects.
            Electrical, mechanical, and structural factors were considered to create the optimal system.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Nevada, Las Vegas
        caption: |
          3.7 GPA
          2021
        sub_title: Bachelors of Science in Electrical Engineering
          #        quote: >
          #          Put a quote describing UNLV here
        description: | # this will include new lines to allow paragraphs
          At UNLV, I gained the project experience to tackle novel problems.

      - layout: left
        title: College of Southern Nevada
        caption: |
          3.4 GPA
          2013
        sub_title: Associate of Science
        description: | # this will include new lines to allow paragraphs
          While I was at CSN, I began tutoring other students which built my confidence in teamwork and independent learning.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
